'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Messages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LM_job.Messages", GetType(Messages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  created, in folder.
        '''</summary>
        Friend Shared ReadOnly Property createIn() As String
            Get
                Return ResourceManager.GetString("createIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Deleted..
        '''</summary>
        Friend Shared ReadOnly Property deleted() As String
            Get
                Return ResourceManager.GetString("deleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Copies.
        '''</summary>
        Friend Shared ReadOnly Property editCopies() As String
            Get
                Return ResourceManager.GetString("editCopies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exist, try another name..
        '''</summary>
        Friend Shared ReadOnly Property existMsg() As String
            Get
                Return ResourceManager.GetString("existMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File .
        '''</summary>
        Friend Shared ReadOnly Property fileMsg() As String
            Get
                Return ResourceManager.GetString("fileMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Folder.
        '''</summary>
        Friend Shared ReadOnly Property folderMsg() As String
            Get
                Return ResourceManager.GetString("folderMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Found: .
        '''</summary>
        Friend Shared ReadOnly Property found() As String
            Get
                Return ResourceManager.GetString("found", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Install or select editing program first.
        '''</summary>
        Friend Shared ReadOnly Property instalOrSelect() As String
            Get
                Return ResourceManager.GetString("instalOrSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Name new project folder.
        '''</summary>
        Friend Shared ReadOnly Property nameFolder() As String
            Get
                Return ResourceManager.GetString("nameFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter a number of copies.
        '''</summary>
        Friend Shared ReadOnly Property numberOfCopies() As String
            Get
                Return ResourceManager.GetString("numberOfCopies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select project folder first.
        '''</summary>
        Friend Shared ReadOnly Property selectFolder() As String
            Get
                Return ResourceManager.GetString("selectFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select label first.
        '''</summary>
        Friend Shared ReadOnly Property selectLabel() As String
            Get
                Return ResourceManager.GetString("selectLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please set file name..
        '''</summary>
        Friend Shared ReadOnly Property setFileName() As String
            Get
                Return ResourceManager.GetString("setFileName", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
